config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users, controllers: {
    confirmations: 'users/confirmations'
  }
  resources :users, except: [:show] do
    resources :appointments
    resources :requests
  end
  resources :subjects, except: [:show]
  resources :profiles, except: [:show]
  resources :tutors do
    member do
      get :appointment
    end
  end
  resources :comments
end

app/controllers/tutors_controller.rb
class TutorsController < ApplicationController
  before_action :set_user, only: %i[show]

  def index
    query = params[:query]

    users =
      if query.present?
        User.tutor.tagged_with(params[:query]).order(:created_at)
      else
        User.tutor.order(:created_at)
      end

    @pagy, @users = pagy(users)
  end

  def appointment
    appointment = Appointment.find_or_create_by(applicant_id: params['userId'], respondent_id: params['tutorId'], status: 'pending')

    respond_to do |format|
      format.js
      format.json { render status: :created }
    end
  end

  def show
    gon.push({
      user_id: current_user.id,
      tutor_id: @user.id,
      appointment_url: appointment_tutor_path
    })

    @pagy, @comments = pagy(@user.comments)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/tutors/index.slim
.card
  .card-header
    h3.card-title All Tutors
    .card-tools
      = form_tag tutors_path, method: :get
        .input-group.input-group-sm style=("width: 250px;")
          = select_tag :query, options_for_select(Subject.all.collect{ |subhect| [subhect.name, subhect.name] }), class: "form-control float-right"
          .input-group-append
            button.btn.btn-default type="submit"
              i.fas.fa-search
  .card-body.table-responsive.p-0
    table.table.table-hover
      thead
        tr
          th Email
          th Subjects
          th
      tbody
        - @users.each do |user|
          tr
            td= user.email
            td= user.subject_list.join(', ')
            td
              = link_to 'View', tutor_path(user), class: "btn btn-info"
  .card-footer.clearfix
    = render partial: 'shared/pagination', locals: { pagy: @pagy }
    == pagy_info(@pagy)

app/views/tutors/show.slim
= content_for(:js) do
  = javascript_pack_tag 'javascript/tutors'

.row
  .col
    .card.card-outline.card-dark
      .card-header
        h3.card-title= @user.username
      .card-body
        = image_tag(@user.image.variant(resize_to_limit: [200, 200]))
        br
        br
        p= "Email: #{@user.email}"
        p= "Phone: #{@user.phone}"
        a href="https://api.whatsapp.com/send?phone=#{@user.phone}" target="_blank"
          | WhatsApp
        - unless current_user.id == @user.id
          div
            btn.btn.btn-primary.js-apply Apply
  .col
    .card.card-outline.card-dark
      .card-header
        h3.card-title Subjects
      .card-body
        p= @user.subject_list.join(', ')
    .card.card-outline.card-dark
      .card-header
        h3.card-title Description
      .card-body
        p= @user.description


.card.card-outline.card-dark
  .card-header
    h3.card-title Comments
  .card-body
    - @comments.each do |comment|
      .card.card-outline.card-dark
        .card-body
          p
            span= comment.sender.username
            span.comment-time #{time_ago_in_words(comment.created_at)} ago
          p= comment.message
  .card-footer.clearfix
    - if current_user.present?
      = simple_form_for [Comment.new] do |f|
        = f.input :sender_id, as: :hidden, input_html: { value: current_user.id }
        = f.input :recipient_id, as: :hidden, input_html: { value: @user.id }
        .form-group
          = f.input :message, label:false, placeholder: 'Add a public comment', input_html: { class: "form-control" }
        = f.button :submit, 'Comment', class: "btn btn-success"