config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users, controllers: {
    confirmations: 'users/confirmations'
  }
  resources :users, except: [:show] do
    resources :appointments
    resources :requests
  end
  resources :subjects, except: [:show]
  resources :profiles, except: [:show]
  resources :tutors do
    member do
      get :appointment
    end
  end
  resources :comments
end

app/models/subject.rb
# == Schema Information
#
# Table name: subjects
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_subjects_on_name  (name) UNIQUE
#
class Subject < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: %i[edit update destroy]

  def index
    @pagy, @subjects = pagy(Subject.all.order(:created_at))
  end

  def new
    @subject = Subject.new
  end

  def edit; end

  def create
    @subject = Subject.new(subject_params)

    if @subject.save
      redirect_to subjects_path, notice: 'Subject was successfully created.'
    else
      render :new
    end
  end

  def update
    if @subject.update(subject_params)
      redirect_to subjects_path, notice: 'Subject was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    if @subject.destroy
      redirect_to subjects_path, notice: 'Subject was successfully destroyed.'
    else
      redirect_to subjects_path, alert: @subject.errors.full_messages.join(', ')
    end
  end

  private

  def set_subject
    @subject = Subject.find(params[:id])
  end

  def subject_params
    params.require(:subject).permit(:name)
  end
end

app/views/subjects/_form.html.slim
.card
  .card-header
    h3.card-title New Subject
  = simple_form_for [subject] do |f|
    .card-body
      .form-group
        = f.input :name, input_html: { class: "form-control" }
    .card-footer
      = f.button :submit, class: "btn btn-success"

app/views/subjects/edit.html.slim
== render 'form', subject: @subject

app/views/subjects/index.html.slim
.card
  .card-header
    h3.card-title All Subjects
    .card-tools
      = link_to 'New Subject', new_subject_path, class: "btn btn-success"
  .card-body.table-responsive.p-0
    table.table.table-hover
      thead
        tr
          th Name
          th
      tbody
        - @subjects.each do |subject|
          tr
            td= subject.name
            td
              .btn-group
                = link_to 'Edit', edit_subject_path(subject), class: "btn btn-info"
                = link_to 'Delete', subject_path(subject), data: { confirm: 'Are you sure?' }, method: :delete, class: "btn btn-danger"
  .card-footer.clearfix
    = render partial: 'shared/pagination', locals: { pagy: @pagy }
    == pagy_info(@pagy)

app/views/subjects/new.html.slim
== render 'form', subject: @subject