config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users, controllers: {
    confirmations: 'users/confirmations'
  }
  resources :users, except: [:show] do
    resources :appointments
    resources :requests
  end
  resources :subjects, except: [:show]
  resources :profiles, except: [:show]
  resources :tutors do
    member do
      get :appointment
    end
  end
  resources :comments
end

app/views/layouts/_changelog.html.slim
- table_height = defined?(height) ? height : 'auto'
.card
  .card-header
    h3.card-title #{object.class.name} Changelog
  .card-body.table-responsive.p-0 style=("height: #{table_height};")
    table.table.table-head-fixed.table-history
      thead
        tr
          th style=("width: 10%;") When
          th style=("width: 10%;") Who
          th style=("width: 10%;") Changed fields
          th style=("width: 35%;") Old Value
          th style=("width: 35%;") New Value
      tbody
        - object.versions.reverse.each_with_index do |version, version_index|
          - version.changeset.each_with_index do |change, i|
            tr class="#{'column-striped' if version_index.even?}"
              td = time_ago_in_words(version.created_at) + ' ago' if i.zero?
              td = version.whodunnit if i.zero?
              td = change[0].humanize
              - if defined?(custom_value) && custom_value
                td = render 'value_field', field: change[0], value: change[1][0]
                td = render 'value_field', field: change[0], value: change[1][1]
              - else
                td = change[1][0]
                td = change[1][1]

app/views/layouts/_content.html.slim
.content-wrapper.px-4.py-2
  - if notice.present?
    .alert.alert-info= notice
  - if alert.present?
    .alert.alert-danger= alert
  = yield

app/views/layouts/_footer.html.slim
footer.main-footer
  strong
    | Copyright © 2019-2019&nbsp;
    a href="#" My Project
    | &nbsp;All rights reserved.
  .float-right.d-none.d-sm-inline
    | v3.0.0

app/views/layouts/_header.html.slim
nav.main-header.navbar.navbar-expand.navbar-white.navbar-light
  ul.navbar-nav
    li.nav-item
      a.nav-link data-widget="pushmenu" href="#"
        i.fas.fa-bars
    li.nav-item.d-none.d-sm-inline-block
      a.nav-link href="#" Home

app/views/layouts/_sidebar.html.slim
aside.main-sidebar.sidebar-dark-primary.elevation-4
  .brand-link.logo-switch
    img.brand-image-xl.logo-xs src="https://adminlte.io/docs/3.0/assets/img/logo-xs.png"
    img.brand-image-xs.logo-xl src="https://adminlte.io/docs/3.0/assets/img/logo-xl.png"
  .sidebar
    - if current_user&.present?
      .user-panel
        .user-image
          - if current_user.image.attached?
            = image_tag(current_user.image.variant(resize_to_limit: [50, 50]))
        .user-info
          p= "Hi, #{current_user.username}"
          p= current_user.role.humanize
    nav.mt-2
      ul.nav.nav-pills.nav-sidebar.flex-column data-widget="treeview" role="menu"
        - if can? :manage, :all
          li.nav-item
            = link_to users_path, class: "nav-link"
              i.nav-icon.fas.fa-users
              p Users
          li.nav-item
            = link_to subjects_path, class: "nav-link"
              i.nav-icon.fas.fa-book
              p Subjects
        - if current_user&.present?
          li.nav-item
            = link_to edit_profile_path(current_user), class: "nav-link"
              i.nav-icon.fas.fa-id-card
              p My Profile
          li.nav-item
            = link_to user_requests_path(current_user), class: "nav-link"
              i.nav-icon.fas.fa-copy
              p Applications
        - if current_user&.present? && current_user.tutor?
          li.nav-item
            = link_to user_appointments_path(current_user), class: "nav-link"
              i.nav-icon.fas.fa-calendar-check
              p Appointments
        li.nav-item
          = link_to tutors_path, class: "nav-link"
            i.nav-icon.fas.fa-user-graduate
            p Tutors
        - if current_user&.present?
          li.nav-item
            a.nav-link href="#{destroy_user_session_path}" data-method="delete" rel="nofollow"
              i.nav-icon.fas.fa-sign-out-alt
              p Logout
        - else
          li.nav-item
            a.nav-link href="#{new_user_registration_path}" rel="nofollow"
              i.nav-icon.fas.fa-user-plus
              p Sign up
          li.nav-item
            a.nav-link href="#{new_user_session_path}" rel="nofollow"
              i.nav-icon.fas.fa-sign-in-alt
              p Sign in

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title App
    = Gon::Base.render_data
    meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible" /
    meta content="width=device-width, initial-scale=1" name="viewport" /
    meta content="yes" name="apple-mobile-web-app-capable" /
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body.sidebar-mini.layout-fixed.layout-navbar-fixed
    .wrapper
      = render 'layouts/header'
      = render 'layouts/sidebar'
      = render 'layouts/content'
      = render 'layouts/footer'
  = yield :js